Update README.md
AlaSQL/alasql pull request #1636
Opened 2023-02-09 11:17 UTC by BirdboyBolu

Thank you for the time you are putting into AlaSQL!

2023-02-11 21:03 UTC, mathiasrw commented on README.md
> +__If you are familiar with SQL, it should be no surprise that proper use of indexes on your tables is essential for good performance.__
thank you fir this improvement

2023-02-11 21:03 UTC, mathiasrw requested changes

2023-02-11 21:03 UTC, mathiasrw commented on README.md
> +This library is perfect for:
Please revert this change

2023-04-28 03:11 UTC, mathiasrw reviewed
Looks good - thanks!

2023-05-22 05:26 UTC, merged

2023-05-30 11:27 UTC, BirdboyBolu commented
Hello @mathiasrw. I hope you are doing great?
I want you to know that I would love to join AlaSQL and handle its technical documentation. It would be great if we can talk more about this. I am willing to join the team, even if you don't have the budget to hire a full-time technical writer. 

My email is ayomide27victor@gmail.com. I look forward to hearing from you soon. Thank you